name: cv-explorer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - numpy=1.24.3
  - opencv=4.7.0
  - matplotlib=3.7.1
  - pillow=9.5.0
  - pip:
    - streamlit==1.20.0 